name: ppo
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - lightning==2.4.0
      - pandas==2.2.3
      - tensorboard==2.18.0
      - xformers==0.0.28.post3
      - rich==13.9.4
      - matplotlib==3.10.1
      - scikit-learn==1.6.1
      - einops==0.8.1
      - ipython
      - gymnasium[box2d]